// Generated by CoffeeScript 1.7.1
(function() {
  App.EmberTableAjaxImageTableCell = Ember.Table.TableCell.extend({
    templateName: 'ember_table/ajax_table/ajax_cell',
    classNames: 'img-table-cell'
  });

}).call(this);
