// Generated by CoffeeScript 1.7.1
(function() {
  require('lib/bootstrap/bootstrap');

  require('lib/antiscroll/antiscroll');

  require('dependencies/ember-addepar-mixins/resize_handler');

  require('dependencies/ember-addepar-mixins/style_bindings');

  require('dist/ember-table');

  require('dependencies/date');

  require('lib/d3/d3');

  require('dependencies/horizon');

  window.App = Ember.Application.create({
    LOG_TRANSITIONS: true
  });

  require('app/data/data');

  require('app/controllers/ajax');

  require('app/controllers/bars');

  require('app/controllers/dynamic_bars');

  require('app/controllers/editable');

  require('app/controllers/financial');

  require('app/controllers/fluid');

  require('app/controllers/horizon');

  require('app/controllers/overview');

  require('app/controllers/simple');

  require('app/controllers/sparkline');

  require('app/controllers/treetable');

  require('app/views/mixins');

  require('app/views/ember_table');

  require('app/views/ember_table/ajax');

  require('app/views/ember_table/bars');

  require('app/views/ember_table/editable');

  require('app/views/ember_table/financial');

  require('app/views/ember_table/horizon');

  require('app/views/ember_table/sparkline');

  require('app/views/ember_table/treetable');

  require('app/router');

  require('app/main');

  require('app/templates');

  window['PR_SHOULD_USE_CONTINUATION'] = false;

}).call(this);
