// Generated by CoffeeScript 1.7.1
(function() {
  App.EmberTableOverviewController = Ember.Controller.extend({
    data: Ember.computed(function() {
      return App.data.treedata;
    })
  });

}).call(this);
