// Generated by CoffeeScript 1.7.1
(function() {
  var _ref;

  require('src/templates');

  Ember.Table = Ember.Namespace.create();

  Ember.Table.VERSION = '0.2.0';

  if ((_ref = Ember.libraries) != null) {
    _ref.register('Ember Table', Ember.Table.VERSION);
  }

  require('dependencies/ember-addepar-mixins/resize_handler');

  require('dependencies/ember-addepar-mixins/style_bindings');

  require('src/utils/jquery_fix');

  require('src/utils/lazy_container_view');

  require('src/utils/utils');

  require('src/column');

  require('src/views');

  require('src/component');

}).call(this);
